### ISSUE TITLE
README.md 中 “感谢” 栏的描述不太符，建议修改或去掉

### ISSUE THREAD

**Issue by KyleBing** [SivanLaai/rime-pure#103]
建议把我的描述修改一下，或者直接去掉：
我啥作者也不是，只是攒(cuán)了个 Rime 的五笔输入方案。
极品五笔、极点五笔的作者另有其人。

![image](https://github.com/SivanLaai/rime-pure/assets/12215982/99a02954-ef88-407d-a820-c3fe7c56abdf)

**Comment by SivanLaai** [comment]
感谢提醒，已经作出修正
