### ISSUE TITLE
[同文3.1.3安卓版][小鹤双拼][如何调用你的手机输入方案？]

### ISSUE THREAD

**Issue by zhl111** [SivanLaai/rime-pure#104]
**提交issue**
我拷贝同文增强版到手机安装目录，提示我载入default.yaml，我重置后运行，没有变化，还是以前的输入方案，

**问题复现（方便的话可以添加现象的截屏/视频方便描述）：**
复现步骤:
1. 拷贝同文增强版到手机安装目录，提示我载入default.yaml
2. 恢复默认设置后，重新部署
3. 同文增强版的皮肤没有启用，仍然是之前的皮肤

**正确的结果**
想使用同文增强版的皮肤设置

**使用设备情况（请完整填写如下信息）：**
 - 设备型号：三星note8
 - 操作系统： 安卓
 - Rime软件名称和版本：同文 3.1.3
 - 输入方案：小鹤双拼
 - 使用皮肤：同文增强版

**其他信息**

**Comment by SivanLaai** [comment]
像这样的问题，我建议发到discussion里面去，太多这样的问题反馈了。对于安装有什么问题可以先看一下这个B站视频 [https://www.bilibili.com/video/BV1YA411z7Um/?spm_id_from=333.999.0.0。](https://www.bilibili.com/video/BV1YA411z7Um/?spm_id_from=333.999.0.0%E3%80%82)
