### ISSUE TITLE
[同文3.2.7][四叶草简体拼音][候选框有很大的方块遮挡]

### ISSUE THREAD

**Issue by Steven52065** [SivanLaai/rime-pure#105]
**提交issue**
把问题清晰的描述清楚

**问题复现（方便的话可以添加现象的截屏/视频方便描述）：**
复现步骤:
![Screenshot_20230731_172048](https://github.com/SivanLaai/rime-pure/assets/36119581/db31f53b-5ce7-4234-9b2f-13157ebd7837)
![Screenshot_20230731_172728](https://github.com/SivanLaai/rime-pure/assets/36119581/5b5552e7-fa17-48b9-8031-8ad5a1e5bea5)
第一张的配色是 暗堂/Dark Temple
第二张的配色是 清风/Cool Breeze
在输入候选框里有一个很大的黑色方块挡着，请问如何去掉呢？

**正确的结果**
按理说应该没有这个方块，直接用一条线隔开就可以了吧

**使用设备情况（请完整填写如下信息）：**
 - 设备型号： Nubia Z50
 - 操作系统： 安卓13
 - Rime软件名称和版本：同文 3.2.7
 - 输入方案：四叶草简体拼音
 - 使用皮肤：同文增强版

**其他信息**

**Comment by chenxiex** [comment]
这个问题我遇到过，重启手机试试？

**Comment by Steven52065** [comment]
> 我遇到过这个问题，重启手机尝试？

重启过很多遍了，一直有这个问题

**Comment by Steven52065** [comment]
找到原因了
这个方块是candidate_separator_color: 候选分割线
但是因为“暗堂”配色没有设置candidate_separator_color这个颜色，就默认fallback到了back_color。
只要给“暗堂”的配色里配置一下
`candidate_separator_color: 0x00000000 #候选分割线颜色（透明）`
就可以把这个方块变成透明的了
（按理说这个分割线应该就是透明的啊，为什么会fallback到back_color呢？）

**Comment by bLUeight** [comment]
我直接把candidate_spacing设为1或1以下也可以了，不会挡住。
