### ISSUE TITLE
[trime 3.2.13][四叶草拼音][缺失flypy.dict.yaml]

### ISSUE THREAD

**Issue by chenxiex** [SivanLaai/rime-pure#107]
**提交issue**
部署时闪退，提示source file rime/flypy.dict.yaml does not exist。安装或不安装小鹤双拼都有这个问题。

**问题复现（方便的话可以添加现象的截屏/视频方便描述）：**
复现步骤:
1. 进入 '软件'
2. 点击 '部署'
3. 出现问题

**正确的结果**
正确完成部署

**使用设备情况（请完整填写如下信息）：**
 - 设备型号： Honor V20
 - 操作系统： 安卓
 - Rime软件名称和版本：同文 3.2.13
 - 输入方案：四叶草拼音
 - 使用皮肤：trime

**其他信息**

**Comment by controlledentropy** [comment]
你可以检查一下默认的default.custom.yaml，把里面的flypy预设方案删掉就可以了。

不过我这里3.2.14部署直接就闪退。哪怕仅仅只部署四叶草基础，部署开始几秒就立即闪退。。。。。
