### ISSUE TITLE
[同文输入法v3.2.14][四叶草拼音][部署闪退]

### ISSUE THREAD

**Issue by chenxiex** [SivanLaai/rime-pure#108]
**提交issue**
部署时闪退

**使用设备情况（请完整填写如下信息）：**
 - 设备型号： 荣耀v20
 - 操作系统： 安卓10
 - Rime软件名称和版本：同文 3.2.14
 - 输入方案：四叶草拼音
 - 使用皮肤：trime

**其他信息**
崩溃日志
[com.osfans.trime-2023-10-10T07_59_42Z.txt](https://github.com/SivanLaai/rime-pure/files/12854399/com.osfans.trime-2023-10-10T07_59_42Z.txt)

**Comment by controlledentropy** [comment]
我的解法是抛弃默认的opencc，仅使用方案配置文件，让3.2.14自己编译opencc文件夹内容。现在基本上我3.2.13的自用布局加上双拼，四叶草和地球使用正常。

不过现在不太满足于双拼的小词库。隔壁IRIME也有个1k stars的方案我之前试用了一下，那个小鹤挂接了扩展词库，可以在双拼中使用清华开源和搜狗的热词词库。刚刚在这个方案里模仿了一下无法生效。但是那个IRIME的方案在trime上水土不服，lua支持不完整很多功能有bug。这个项目相比之下使用了小鹤官方的码表字典，比较稳定。我要研究一下怎么能让小鹤使用扩展词库。

**Comment by chenxiex** [comment]
> 我的解法是抛弃默认的opencc，仅使用方案配置文件，让3.2.14自己编译opencc文件夹内容。现在基本上我3.2.13的自用布局加上双拼，四叶草和地球使用正常。
> 
> 不过现在不太满足于双拼的小词库。隔壁IRIME也有个1k stars的方案我之前试用了一下，那个小鹤挂接了扩展词库，可以在双拼中使用清华开源和搜狗的热词词库。刚刚在这个方案里模仿了一下无法生效。但是那个IRIME的方案在trime上水土不服，lua支持不完整很多功能有bug。这个项目相比之下使用了小鹤官方的码表字典，比较稳定。我要研究一下怎么能让小鹤使用扩展词库。

确实，在删除opencc文件夹之后部署不会闪退了，还快了很多。没有做其他更改，目前没有发现任何副作用。

**Comment by controlledentropy** [comment]
> 确实，在删除opencc文件夹之后部署不会闪退了，还快了很多。没有做其他更改，目前没有发现任何副作用。

实际上我是推荐trime用户都跟进新版本的，新版本在积极重构原来的代码，虽然来日方长，对原来的配置兼容也有一些问题（我是在3.2.3跳跃到3.2.12后痛下决心两周给自己按照新版本的特性折腾了一套滑动输入布局所以没包袱XD），但是性能的提升是必然的，而且滑动输入终于可以正常使用了，基本赶上成熟输入法的体验了。

目前新版本开发比较乏力，人手少任务重，如果用户都停留在老版本，这样无论是公开的提交合并还是bug反馈都会很少导致项目进度太慢最后用户和开源贡献双双弃坑，trime就算是完了。。。。就目前而言高度可定制又开源的输入法大概只有rime了。死掉是真的会很可惜
