### ISSUE TITLE
[同文输入法v3.2.14][小鹤拼音][使用第三方扩充词库]

### ISSUE THREAD

**Issue by controlledentropy** [SivanLaai/rime-pure#109]
**Is your feature request related to a problem? Please describe.**
大佬有没有方法给小鹤双拼方案加载第三方扩充词库。我这里按照正常的词库扩充方式尝试了下无法生效。

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
我尝试使用如下链接的项目里的做法，把扩展词库加到了四叶草拼音上，可以生效
但是将相同扩展词库应用在双拼方案里就无法生效了。默认的词库排序很有问题，常用字的权重非常离谱。参照该项目中对双拼的修改方法试了试，发现还是无法实现扩展字典的正常挂载。但直接使用该作者的方案是可以正常使用双拼打出扩展字典中的词条的。
(https://github.com/DreamAfar/Rime-IME-for-iOS-iRime)

大佬能否给点思路，如何在您当前方案内让双拼也能调用地球拼音的扩展词库，来完成成语，诗句等热词的候选。

**Comment by SivanLaai** [comment]
加载第三方词库，你可以在https://github.com/SivanLaai/rime-pure/blob/master/schemes/%E5%B0%8F%E9%B9%A4%E9%9F%B3%E5%BD%A2/flypy_user.txt里面自己加进去，你说的加载第三方的，因为小鹤双拼官方只给出了二进制文件，会受限。

**Comment by controlledentropy** [comment]
> 加载第三方词库，你可以在[这里]里面自己加进去，你说的加载第三方的，因为小鹤双拼官方只给出了二进制文件，会受限。
> 
> 1。具体怎么做的，你把配置发出来看看，你怎么做的。
> 
> 2。还有你说的默认词序是小鹤的吗？

[感谢大佬回复XD。我尝试把地球拼音的方案中的词库import_tables贴到小鹤里，果然是不行，官方的二进制码表之前就记得很难搞。不过 
 [这个](https://github.com/DreamAfar/Rime-IME-for-iOS-iRime)项目里的作者确实实现了小鹤双拼调用扩展词库，好像是自己重写了码表还是什么的，用起来就像是双拼先转了全拼然后调用拼音的扩展词库一样，使用上的体验就是双拼版拼音（没有四码上屏，类似连打但可以逐字像全拼一样选词）。目前我pc上使用的这套方案，功能比较强可以实时翻译简短的中英词汇，集成了一些lua功能。但这套面向irime的配置可以在鼠须管上用，trime却半残，而且最近出现用户词库频繁丢失词条的问题，就找到了大佬的方案。现在准备切过来。

次序的问题是我尝试把小鹤音形改名和双拼共存导致的奇怪问题，也有可能是我一段时间已经习惯了上面那个项目里的连打选词，生僻字被过滤了所以没怎么选词，现在切回来原生的小鹤词库选常用字有点抓狂。

另外我刚刚清空了rime目录重新应用了一下大佬的双拼方案，发现输入过的词条后面有太极标，莫非是大佬也集成了用户词固化到dict文件里的功能？

**Comment by SivanLaai** [comment]
好的，我关注一下，最近这段时间有点忙，后面时间多的时候，我准备把键盘适配一下最新的同文，解决一些反馈的重点问题，感谢反馈。

**Comment by SivanLaai** [comment]
另外你用的是哪个方案是小鹤双拼还是小鹤音形？小鹤音形的话默认是四码上屏并记录词汇的，小鹤双拼是支持连打选字的。

**Comment by controlledentropy** [comment]
> 用的是哪个方案是小鹤双拼还是小鹤音形？小鹤音形的话默认是四码上屏并记录词汇的，小鹤双拼是支持连打选字的

目前使用双拼方案，但是发现当前的双拼方案还是音形的匹配，连打越打候选越少，基本只和音形差一个四吗自动上屏幕。tab也无法对单字候选，无法组合常用的词汇。总之就是双拼方案依然是按照音形的规则来匹配单字了，不是双拼那种语句流或连打的感觉。

上面那个老哥的纯双拼方案接上扩展词库就比较爽，可以分字分词翻页选，也能通过双拼的首声母匹配所有得词库词条比如诗句、热词成语等，匹配长句的过程中不会拐到鹤形上去从而被打断。

例如输入uuu，候选会出现事实胜于雄辩 ~b，但uuuy就只匹配了’叔’，而uuuyxb则完全匹配不到长句，uiuiugyuxsbm也是匹配不到。不过我的了解非常有限，所以不知道如何下手，就当前方案里的小鹤方案使用效果来讲，两个都是更多偏向音形了，偏向单字输入而不是整词整句加分词匹配的连贯输入，不熟悉音形的基本没法正常使用，会被形码匹配卡emo XDrz

**Comment by controlledentropy** [comment]
https://github.com/DreamAfar/Rime-IME-for-iOS-iRime/issues/2#issuecomment-1758979135

**Comment by SivanLaai** [comment]
知道了，感谢反馈，这块因为字典二进制是官方的，目前没有办法去除最后的笔画位，照你的这个意思应该是不要形的小鹤，我过段时间研究一下，看是否有解决方案。

**Comment by SivanLaai** [comment]
这个需要小鹤的码表才好实现，暂时先关闭，
