### ISSUE TITLE
[同文][四叶草九宫格]切换到九宫格布局主题后还是全键盘且无法输入中文

### ISSUE THREAD

**Issue by hityb** [SivanLaai/rime-pure#113]
**提交issue**
同文输入法，部署trime配置之后，方案勾选四叶草简体拼音和四叶草九宫格，使用tongwenfeng主题，长按菜单选择方案为四叶草九宫格，选择之后，键盘布局未发生变化，按字母按钮不会出现中文候选字词。

**问题复现（方便的话可以添加现象的截屏/视频方便描述）：**
复现步骤:

**正确的结果**
选择四叶草九宫格方案后，键盘变成九宫格布局，且能正常输入中文。

**使用设备情况（请完整填写如下信息）：**
 - 设备型号： Redmi K60 Pro
 - 操作系统： 安卓
 - Rime软件名称和版本：同文 3.2.15
 - 输入方案：四叶草九宫格
 - 使用皮肤：tongwenfeng

**其他信息**

**Comment by hityb** [comment]
我把同文回退到3.2.9就能正常了。
请确认一下是同文到问题还是配置到问题。确认后请关闭该issue。

**Comment by SivanLaai** [comment]
最新的同文，改的太过激进了。
