### ISSUE TITLE
ios 仓输入法

### ISSUE THREAD

**Issue by Nana2222** [SivanLaai/rime-pure#116]
请问是否支持ios仓输入法配置？试用了两个都没有九宫格

**Comment by SivanLaai** [comment]
不支持，因为我是用的安卓同文，没有IOS适配，所有只有词库可以共用的

**Comment by Nana2222** [comment]
大佬什么时候支持了告诉一声，你的项目挺好用的



| |
James
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月29日 15:23 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [SivanLaai/rime-pure] ios 仓输入法 (Issue #116) |

不支持，因为我是用的安卓同文，没有IOS适配，所有只有词库可以共用的
