### ISSUE TITLE
[trime 3.2.9][同文风增强版][剪贴板没有内容]

### ISSUE THREAD

**Issue by myCodingTrip** [SivanLaai/rime-pure#124]
**提交issue**
长按V调出的剪贴板没有内容，切换到旁边的“中文”让后再切换回来就有了

**正确的结果**
长按V调出的剪贴板有相应的内容

**使用设备情况（请完整填写如下信息）：**
 - 设备型号： 三星S22
 - 操作系统： 安卓14
 - Rime软件名称和版本：同文 3.2.9
 - 输入方案：四叶草拼音
 - 使用皮肤：同文风增强版

**Comment by SivanLaai** [comment]
英文的V就是没有这个功能，因为底层相当于换了一个键盘。
