### ISSUE TITLE
四叶草配置多音字

### ISSUE THREAD

**Issue by linGinc** [SivanLaai/rime-pure#35]
四叶草配置中，打“朝”，zhao，没有这个字，但打“朝阳”就有，自己已经在字典中加入了，希望配置中也可以加入

**Comment by walthao** [comment]
四叶草里很多多音字都有问题，比如“行”、“弹”，但是我看四叶草原始项目fkxxyz/rime-cloverpinyin是有这些多音字的，望修复

**Comment by SivanLaai** [comment]
这些多音字已经加入了的，release现在还没有更新，你用的是最新的方案文件新部署就可以。如下所示：
朝
![image](https://user-images.githubusercontent.com/33414148/129123365-a784f0c9-b01b-4da3-a6d3-b5c011608453.png)
![image](https://user-images.githubusercontent.com/33414148/129123386-546c9bd1-162b-4069-b70a-cdfe5ba58ba5.png)
行
![image](https://user-images.githubusercontent.com/33414148/129123433-edafceb6-d270-40fe-96b8-49dbe08755fe.png)
![image](https://user-images.githubusercontent.com/33414148/129123468-a3fce693-478e-4594-b742-15741dd44bde.png)
弹
![image](https://user-images.githubusercontent.com/33414148/129123480-ef8d46de-ecc1-4032-af29-fdafe9ce9ecf.png)
![image](https://user-images.githubusercontent.com/33414148/129123503-bc745ff9-8d99-4dca-b188-841d3435d1ef.png)
