### ISSUE TITLE
最近的提交是不是出错了 我看修改错误的地方没变啊

### ISSUE THREAD

**Issue by spphinslove** [SivanLaai/rime-pure#36]
fantan 还是打不出。我看文件也没有改啊 是不是搞错文件了？

**Comment by spphinslove** [comment]
![图片](https://user-images.githubusercontent.com/11383988/128746045-0d2eac03-bc3f-4d92-a6be-32191ef44965.png)

**Comment by spphinslove** [comment]
这次的有问题 上次的commit就能打出 反弹。我好像还发现“命令行”有关的 命令行参数	ming ling xing can shu	12934等等

**Comment by SivanLaai** [comment]
没有错的，上次的修改就没有涉及到这个字典，这个需要修正。这个是大字典，他修改的是小字典。

**Comment by spphinslove** [comment]
![图片](https://user-images.githubusercontent.com/11383988/128803021-79627ef6-400c-4a49-8f1a-7552a66411f4.png)
这次commit就能打出反弹 下调。最新的commit我打不出的。

**Comment by SivanLaai** [comment]
去重了，只保留了大字典里的词组。
