### ISSUE TITLE
感谢及一个请求

### ISSUE THREAD

**Issue by vangoah20** [SivanLaai/rime-pure#37]
您好，能否基于四叶草的词库生成一份地球拼音可用的带调拼音字库？

**Comment by SivanLaai** [comment]
多谢反馈，我尽量抽时间整理一个出来

**Comment by SivanLaai** [comment]
![image](https://user-images.githubusercontent.com/33414148/131670446-5d9b6245-70cc-4ed0-8b6e-0667a56f06e7.png)
已经完成了这个工作，这个比我想象地难很多😂️，一共前前后后零零碎碎花了有十来天的时间，点个赞支持下本项目，或者传播下本项目，同时也可以加入到项目维护中来😄️。
