### ISSUE TITLE
同文端打单字好像打不出来

### ISSUE THREAD

**Issue by Lzyj07** [SivanLaai/rime-pure#38]
比如打“bu” 出来的结果没有“不”，在很后面有“不不”的词组
打“hui”不出来“会”，打“自带的配置”，出来的是“自带德配置”，并且打“的”出不来，只能出来“的的”好像把每一个开头的高频词都吃掉了？
不知道是我配置的哪里有问题

**Comment by SivanLaai** [comment]
修改了这个问题，我自己写了个爬虫优化了原来四叶草依赖的拼音标注项目，没有吃词频的情况了，在百度词库的基础上修复了很多词组，比如弹出，上调这些词组的标注错误。同时不能支持了词组多音字的标注，弹出（dan chu）、弹出（tan chu）其实是对的。
![image](https://user-images.githubusercontent.com/33414148/131220659-1ae5e480-1af7-4076-b2c8-7386ec3d6cb5.png)
