### ISSUE TITLE
四叶草九宫格使用中遇到的问题

### ISSUE THREAD

**Issue by gghubgg** [SivanLaai/rime-pure#40]
一 输入符号，只能默认是英文符号。从符号那里返回，只能返回到中文。

二 常常自动加入逗号。

三 在候选词那里，常常点击两下才能上屏。

四 想在中文输入状态的每个按键上加入长按选择输入符号的功能，不知道怎样设置。

五 不知道怎样在输入状态加入词语。

**Comment by SivanLaai** [comment]
1. 输入符号，在候选栏最右边有中英切换，切换后可以正常的输入中英符号
2. 常常自动加入逗号，这个是什么问题，我好像没有遇到，是不是按到了逗号键，或者详细的录个屏发来看看
3. 点击两下上屏，这个和方案没有关系，我一直在手机上使用没有你说的这种情况，你是用的哪个版本的同文？最好更新最新的版本
4. 这个要修改同文的yaml配置文件，https://github.com/SivanLaai/rime-pure/blob/master/trime/rime/%E5%90%8C%E6%96%87%E9%A3%8E%E5%A2%9E%E5%BC%BA%E7%89%88.trime.yaml
5. 这个是加入自定义词语还是什么？感觉表述的有点模糊，如果是自定义的话，你多输入几次就会被加入到自定义词典里了，不需要你手动处理，当然你也可以加入一些你自己手动添加的词语。
