### ISSUE TITLE
最新的 按下D没有候选词

### ISSUE THREAD

**Issue by spphinslove** [SivanLaai/rime-pure#46]
比如想敲“的“ 一般按D 就行了

**Comment by SivanLaai** [comment]
暂时先使用老版本的，这个问题看了下感觉不是小问题

**Comment by king0billy** [comment]
剪切板、历史记录栏 调不出来啊，
“隐藏输入法：全键盘状态下按键G向下滑，九宫格状态下按分词键向下滑
编辑功能：全键盘状态下长按G，九宫格状态下按编辑键，可实现复制粘贴拷贝等功能”

这两个没有反应，还有我用的是谷哥play上最新的3.1.3版本的同文
