### ISSUE TITLE
【多音字问题】bian yi 便宜

### ISSUE THREAD

**Issue by Direct-A** [SivanLaai/rime-pure#48]
便宜并不能直接通过 pian yi 得到提示
bian yi 却可以，是不是有多音字的都会有这个问题啊
比如之前的 dan chu 弹出

**Comment by SivanLaai** [comment]
这个比较好理解，就是便宜这个词汇在当前的词库里有两种读音，详见[百度词典](https://hanyu.baidu.com/s?wd=%E4%BE%BF%E5%AE%9C&device=pc&from=home)，当前的所有词组拼音数据都是利用爬虫从百度词典抓取。便宜分成了```便宜```，现在已经覆盖了百度词库的所有词语，并且只保留了首选的最大拼音，也就是bian yi，目前看来百度词典并不是按照常见词频排序的。和之前的dan chu是两回事。

**Comment by SivanLaai** [comment]
这一块主要涉及到这两个项目https://github.com/SivanLaai/BaiduPinyinCrawler和https://github.com/SivanLaai/exact-pinyin-mark，前者是爬虫主程序，后者是拼音生成工具。

**Comment by king0billy** [comment]
那能不能出一个多音词的完整编译release版本

**Comment by SivanLaai** [comment]
这块工作要做好的话要使用机器学习的标注方法来做，可能可以做到比较高的准确率，然后在加字典，鉴于工作量较大，我先往后放一放。

**Comment by fevenor** [comment]
“银行”应该只有yín háng这一种读音吧，四叶草地球拼音中是 yin2 xing2

**Comment by Eyion** [comment]
这种情况得到改善了吗？

**Comment by SivanLaai** [comment]
现在使用了新的词库，这一块暂时解决。
