### ISSUE TITLE
关于小鹤双拼的设置问题以及几个建议

### ISSUE THREAD

**Issue by ECJRO** [SivanLaai/rime-pure#50]
平台为Windows 11 PC，首次安装小狼毫，只含有本仓库提供的配置文件。

还是第一次用这样结果能够自动上屏的小鹤双拼，此前从来没见过这样的操作，于是也有很多问题想问：

1、因为在自动上屏的同时看到好像是提示码的东西，然后打某些单字和词组出不来（例如「的」和「为什么」），所以怀疑默认为小鹤音形？**那么如何设置为只用拼音的小鹤双拼而不是小鹤音形**？（也尝试过学习小鹤音形，但是小鹤官网的音形学习教程在科普一样东西的同时疯狂引入不加解释的新概念和自创的词语，我个人实在是看不懂也学不来）
在flypy.schema中已经看到「四码上屏」「自动上屏」等配置，但是不清楚要还原为只用拼音的小鹤双拼需要改动哪些配置。
本仓库的issue中 https://github.com/SivanLaai/rime-pure/issues/3 提到自然码，然而众所周知想转换双拼方案真的很痛苦。
2、是否有考虑自带「拆字」字库？
3、是否有考虑自带readme.md页面中展示的几个Win 10风格皮肤？自己在默认配色方案上[配置](https://zhuanlan.zhihu.com/p/265794084 )应该也没问题，不过如果能自带的话会更方便。

**Comment by SivanLaai** [comment]
感谢支持和反馈，最近在忙考试，等忙完会更新一下。

**Comment by Jacobax** [comment]
似乎小鹤双拼实际是小鹤音型

**Comment by Frank997** [comment]
> 感谢支持和反馈，最近在忙考试，等忙完会更新一下。这个应该是带形的版本，你是说只要纯音不要形的吧？

手机端也期待有不带形的小鹤双拼！最好还有模糊输入，手机精准输入字母太痛苦了，用音形时尤其明显。

先谢谢作者！这个仓库对于我这种不懂trime配置的用户真的很有帮助！感谢！

**Comment by hlwfze** [comment]
不知道能否纯双拼但是也可以音形选词

**Comment by SivanLaai** [comment]
> > 感谢支持和反馈，最近在忙考试，等忙完会更新一下。这个应该是带形的版本，你是说只要纯音不要形的吧？
> 
> 手机端也期待有不带形的小鹤双拼！最好还有模糊输入，手机精准输入字母太痛苦了，用音形时尤其明显。
> 
> 先谢谢作者！这个仓库对于我这种不懂trime配置的用户真的很有帮助！感谢！

这个诉求是需要做到长输入吗？

**Comment by hlwfze** [comment]
是的吧 双拼就和拼音一样基本，音形是四码上屏

**Comment by SivanLaai** [comment]
已经更新小鹤双拼为长句输入：
![image](https://user-images.githubusercontent.com/33414148/218253361-9ed920b4-1903-4bef-bd36-4f8b34e9d07e.png)
把原来的小鹤改成了小鹤音形，感谢提供反馈。

**Comment by SivanLaai** [comment]
长句版本的小鹤请查看https://github.com/SivanLaai/rime-pure/tree/master/schemes/%E5%B0%8F%E9%B9%A4%E5%8F%8C%E6%8B%BC
