### ISSUE TITLE
四叶草26键方案下候选词翻页难受

### ISSUE THREAD

**Issue by chenxiex** [SivanLaai/rime-pure#51]
基本上不可能在屏幕里面显示完一页的候选词，这样就要左右滑动来查看，滑到最右之后又要手动翻页，就很麻烦。能不能做成全是滑动。

**Comment by SivanLaai** [comment]
打字的时候，翻页可以使用逗号向上翻页，句号向下翻页。你说的这个是要在同文的前端修改，难度还比较大。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月24日 17:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [SivanLaai/rime-pure] 四叶草26键方案下候选词翻页难受 (Issue #51) |

基本上不可能在屏幕里面显示完一页的候选词，这样就要左右滑动来查看，滑到最右之后又要手动翻页，就很麻烦。能不能做成全是滑动。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenxiex** [comment]
还有一个问题是翻页之后候选词不会自动回复到最左边，这样导致每次翻页之后我都要滑动到最左边，然后再滑动回最右边，这样才能看完这一页的所有候选词。
这是同文的bug吗？如果是的话我就到那边去反馈看看了。

**Comment by SivanLaai** [comment]
对，也是在同文端的问题。
在2022年1月24日 ***@***.***> 写道：

还有一个问题是翻页之后候选词不会自动回复到最左边，这样导致每次翻页之后我都要滑动到最左边，然后再滑动回最右边，这样才能看完这一页的所有候选词。
这是同文的bug吗？如果是的话我就到那边去反馈看看了。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
