### ISSUE TITLE
建议clover🍀四叶草yaml文件分割

### ISSUE THREAD

**Issue by quanh** [SivanLaai/rime-pure#52]
建议分割**dict.yaml** 文件， 比如：
`clover.base.dict.yaml` 、 `clover.phrase.dict.yaml`， 比如分割为常用字、生僻字等

原因：dict 文件很大，而且其中很多字符存在unix 和 windows不兼容的情况
已知， Mac、Ubuntu 上有很多生僻字无法展示 `𣍰` ， 分割出去可以更好组织

**Comment by SivanLaai** [comment]
收到建议，我最近学业比较繁忙，你这边是否有时间，可以加入到这个项目中来，一起维护，帮助更多的人。作者栏也可以加上你，召唤更多的人来建立这个项目。

**Comment by quanh** [comment]
有空我会先整理一下，先分割一个版本

**Comment by quanh** [comment]
@SivanLaai  已经完成对 `clover.base.dict.yaml`码表的分割，主要是规范表的整理， 资源见：
https://github.com/quanh/chinese-char-dict

**Comment by SivanLaai** [comment]
能按照本项目风格提一个merge过来，写好说明文档，我给合并到主分支吗？在项目文档你可以链接你的源项目就行。
