### ISSUE TITLE
同文风增强版主题的剪贴板太深了

### ISSUE THREAD

**Issue by Jacobax** [SivanLaai/rime-pure#53]
需要三步才能到达不方便

**Comment by Jacobax** [comment]
如果可以的话就谢上加谢了：
请求加一个gboard配色
请求加入英文联想

**Comment by SivanLaai** [comment]
好的，我找一个时间加上去，最近比较忙，抱歉。

**Comment by SivanLaai** [comment]
已经添加了，
一次按键就可以到剪切板：全键盘状态下长按V键，九宫格状态下长按符键
https://github.com/SivanLaai/rime-pure#%E5%90%8C%E6%96%87%E7%AB%AF

**Comment by Jacobax** [comment]
> 已经添加了，
> 一次按键就可以到剪切板：全键盘状态下长按V键，九宫格状态下长按符键
> https://github.com/SivanLaai/rime-pure#%E5%90%8C%E6%96%87%E7%AB%AF

强！感谢付出
