### ISSUE TITLE
自造词与词频调整问题

### ISSUE THREAD

**Issue by chenxiex** [SivanLaai/rime-pure#55]
当我输入一个新词（比如“原神”）的时候，这个新词不会被立即记录。输入多次之后仍是如此。而且词频调整好像也比较迟钝，要输入很多次才会有词频调整。是否有办法调节记录新词和词频调整的灵敏度？

**Comment by SivanLaai** [comment]
你用的什么方案，是拼音嘛，我在九宫上测试是有效的，可以生成新词和词频的。

**Comment by chenxiex** [comment]
> 你用的什么方案，是拼音嘛，我在九宫上测试是有效的，可以生成新词和词频的。

我这里换成3.2.5版本就没问题了，3.2.2及一下版本在我这里都会出问题。原因不明。

**Comment by SivanLaai** [comment]
感谢反馈

**Comment by SivanLaai** [comment]
> 2.

九宫格有什么问题，我这里九宫格是可以在最新版本上正常使用的，可以正常的加词。

**Comment by chenxiex** [comment]
> > 
> 
> 九宫格有什么问题，我这里九宫格是可以在最新版本上正常使用的，可以正常的加词。

咦README不是说九宫格必须在3.2.0以下版本使用吗？

**Comment by SivanLaai** [comment]
已经更新，最新的同文已经不存在这样的问题了。

**Comment by SivanLaai** [comment]
应该是没有更新😂



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月12日 17:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [SivanLaai/rime-pure] 自造词与词频调整问题 (Issue #55) |

九宫格有什么问题，我这里九宫格是可以在最新版本上正常使用的，可以正常的加词。

咦README不是说九宫格必须在3.2.0以下版本使用吗？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
