### ISSUE TITLE
trime 3.2.5重新部署会闪退崩溃

### ISSUE THREAD

**Issue by sunwgit** [SivanLaai/rime-pure#56]
Q：手机品牌？
A：一加6

Q：手机系统？
A：Android 10 / H2OS 10.0.11

Q：trime 版本？
A：3.2.5 

Q：安装来源、平台？
A：从 F-Droid平台下载安装 

Q：安装了什么方案？
A：按本方案安装说明安装了『四叶草拼音』和『四叶草九宫格』且只完成了这两步：
<img width="729" alt="image" src="https://user-images.githubusercontent.com/11364780/158137077-fbb05549-baba-4849-bf1e-febc52a7883c.png">

Q: 是怎么崩溃的？
A: 每次选择完方案后点击『部署』按钮，紧接着就会闪退

**Comment by SivanLaai** [comment]
电脑端会崩溃嘛，你把你的文件目录sdcard/rime给我看下

**Comment by sunwgit** [comment]
> 电脑端会崩溃嘛，你把你的文件目录sdcard/rime给我看下

- 电脑端没用这个
- 我手机的`sdcard/rime`怎么给你看?

**Comment by SivanLaai** [comment]
直接截图给我看

**Comment by sunwgit** [comment]
> 直接截图给我看

![Screenshot_20220317-085359.jpg](https://user-images.githubusercontent.com/11364780/158723843-af216c8f-51b0-4de1-b889-3051eb7e33a9.jpg)

**Comment by yjh-bill** [comment]
有同样的问题

**Comment by yjh-bill** [comment]
来回折腾了一下，好像是opencc的问题。如果把opencc用release里的opencc覆盖掉，那么重新部署就会闪退; 如果保留自带的opencc，就没问题

**Comment by SivanLaai** [comment]
> 

opencc里面主要是繁简转换，去掉看能不能正常使用繁简转换功能

**Comment by yjh-bill** [comment]
试了一下，可以打繁体（没有覆盖trime自带的opencc）

**Comment by sunwgit** [comment]
经楼上提醒,我直接删掉了opencc,现在没得问题了,当然确实不能输入繁体.

如果找原版trime的opencc替换上去应该没得问题,但是太麻烦了,所以我直接删了.

结论: `如果不用输入繁体字,删了opencc也没的问题`

**Comment by SivanLaai** [comment]
感谢@(sunwgit)[https://github.com/sunwgit]提供方案
