### ISSUE TITLE
「Trime疑问」模糊音相关

### ISSUE THREAD

**Issue by Fiilltt** [SivanLaai/rime-pure#58]
系统：Android  Trime：3.2.5
  想问一下大大，这个四叶草九宫格的输入方案可以添加模糊音规则吗？（我按照PC的模糊音设置来覆盖文档后，发现用九宫格打字不显示文字了）  是不是只能26键的才能用模糊音啊？

  PS：感谢大佬提供的输入方案，巨好用，大佬辛苦啦。

**Comment by snakeman152** [comment]
大佬，在手机同文上，九宫格无法显示，我是直接压缩包替换的

**Comment by Fiilltt** [comment]
> 我已经知道哪里问题了,是主题的问题

噢噢好的 大佬牛的

**Comment by SivanLaai** [comment]
感谢分享解决方案
