### ISSUE TITLE
小狼毫下面简繁切换快捷键好像不起作用

### ISSUE THREAD

**Issue by nodesiremonk** [SivanLaai/rime-pure#61]
在Windows 10下面小狼毫最新版本（0.14.3）使用最新的发布版：[rime_pure V1.1.6](https://github.com/SivanLaai/rime-pure/releases/tag/1.1.6)

按下简繁切换的快捷键（Ctrl+Shift+4），有出现“汉字”和”漢字“的交替提示，但好像并没有实际切换输入模式，当前是简体的还是继续出简体，当前是繁体的还是出繁体字。通过 Ctrl + ` 打开菜单一步步切换的时候是好的。请问是不是我哪里没有设置对？谢谢！

**Comment by king0billy** [comment]
剪切板、历史记录栏 调不出来啊，
“隐藏输入法：全键盘状态下按键G向下滑，九宫格状态下按分词键向下滑
编辑功能：全键盘状态下长按G，九宫格状态下按编辑键，可实现复制粘贴拷贝等功能”

这两个没有反应，还有我用的是谷哥play上最新的3.1.3版本的同文

**Comment by king0billy** [comment]
剪切板、历史记录栏 调不出来啊，
“隐藏输入法：全键盘状态下按键G向下滑，九宫格状态下按分词键向下滑
编辑功能：全键盘状态下长按G，九宫格状态下按编辑键，可实现复制粘贴拷贝等功能”

这两个没有反应，还有我用的是谷哥play上最新的3.1.3版本的同文
