### ISSUE TITLE
有时候不知道按什么键能调出带有上下左右按键的编辑器，难以复现

### ISSUE THREAD

**Issue by king0billy** [SivanLaai/rime-pure#62]
剪切板、历史记录栏 调不出来啊！！！

“隐藏输入法：全键盘状态下按键G向下滑，九宫格状态下按分词键向下滑
编辑功能：全键盘状态下长按G，九宫格状态下按编辑键，可实现复制粘贴拷贝等功能”

想调出带有上下左右按键的编辑器，但是按这两个操作没有反应，还有我用的是谷哥play上最新的3.1.3版本的同文。更新了3.2.2还是一样。

**Comment by SivanLaai** [comment]
剪切板是，全键盘状态下长按V键，九宫格状态下长按符键
