### ISSUE TITLE
四叶草九宫格产生的user.txt无法被其他平台的同步接受

### ISSUE THREAD

**Issue by dvorak0** [SivanLaai/rime-pure#64]
非常棒的配置！感谢作者

同文输入法记录的我的用户词典信息在`user.txt`。而`fcitx-rime`在同步时，只会选择`*.userdb.txt`文件同步。

请问如何解决这个问题。

**Comment by SivanLaai** [comment]
fcitx-rime你的方案配置是一样的嘛，就是这个输入法的核心就是rime，所以只要rime的配置一样应该是不会有问题的。请提供下fcitx-rime的方案和配置。

**Comment by dvorak0** [comment]
> fcitx-rime你的方案配置是一样的嘛，就是这个输入法的核心就是rime，所以只要rime的配置一样应该是不会有问题的。请提供下fcitx-rime的方案和配置。

不是一样的，因为pc上我用的不是九宫格，用的是luna_pinyin，同文上用的是四叶草九宫格。即使是这样配置，其实pc上的同步，会去同步目录中找到所有的*.userdb.txt来同步，包括luna_pinyin.userdb.txt和clover.userdb.txt。即使我在同文上并不使用luna_pinyin。

昨天我试了一个方法可以解决这个问题：我把https://github.com/SivanLaai/rime-pure/blob/2449771bee27916483b17f6f61ecbf462e0c75f2/schemes/Clover%E5%9B%9B%E5%8F%B6%E8%8D%89%E4%B9%9D%E5%AE%AB%E6%8B%BC%E9%9F%B3/clover_jiugong.schema.yaml#L76 整个部分，换成了跟https://github.com/SivanLaai/rime-pure/blob/2449771bee27916483b17f6f61ecbf462e0c75f2/schemes/Clover%E5%9B%9B%E5%8F%B6%E8%8D%89%E6%8B%BC%E9%9F%B3/clover.schema.yaml#L116 一样。

这样，我能看到我自己的词库信息会出现在clover.userdb.txt。所以pc端也就可以导入这部分词库了。

不知道这样是否合理。

**Comment by SivanLaai** [comment]
修改配置就行，可以使用就是合理，这个问题先关闭了，有问题可以在重开。
