### ISSUE TITLE
四个bug。详情见图床！

### ISSUE THREAD

**Issue by king0billy** [SivanLaai/rime-pure#65]
剪切板、历史记录栏 等等重要功能调不出来啊！！！

1.“隐藏输入法：全键盘状态下按键G向下滑，九宫格状态下按分词键向下滑
编辑功能：全键盘状态下长按G，九宫格状态下按编辑键，可实现复制粘贴拷贝等功能”
——想调出带有上下左右按键的编辑器，但是按这两个操作没有反应，还有我用的是谷哥play上最新的3.1.3版本的同文。更新了3.2.2还是一样。[20220419003019.jpg](https://postimg.cc/sv05ZtJ7)

2.“剪切板是，全键盘状态下长按V键，九宫格状态下长按符键” 
——按v只是paste粘贴键！下面是具体情况！【有部分配置和选项信息】：
[ezgif-2-0d9e0b1940.gif](https://postimg.cc/zLQwZ4yq)

3. 长按b键卡死
——
[ezgif-2-c9b0f25df3.gif](https://postimg.cc/pmp4fMMH)

4.更新同文输入法版本之后， 打字出 图片和符号 的功能无法使用

**Comment by SivanLaai** [comment]
感谢反馈问题，已经详细的说明和复现，这个问题是因为小先生是另外一个主题了，所有的功能都在同文增强版本里面，这些添加的主题是第三方的，我没有修改

**Comment by king0billy** [comment]
换了同文增强版之后，

1.“剪切板是，全键盘状态下长按V键，九宫格状态下长按符键”
——按v只是破折号

2.打字出表情功能无法使用

[c03e9271e756d419812390371d0a394b.gif](https://postimg.cc/PCHGpd6J)

**Comment by SivanLaai** [comment]
你有没有更新到最新的同文版本，目前只有最新的同文支持
