### ISSUE TITLE
OpenCC有重复项目导致Trime同文输入法无法正确部署

### ISSUE THREAD

**Issue by xqqy** [SivanLaai/rime-pure#66]
# 发生了什么
受opencc文件夹中symbol_word.txt与emoji_word.txt中存在的怕「平方厘米」、「污染」、「Km」（和它附近的一个词汇）有重复的缘故，导致整体输入法在部署到Android同文输入法时，会导致整个同文输入法错误退出。

# 解决方案
删掉这些文件中的重复词汇并使用opencc进行检查以确保安全。

**Comment by SivanLaai** [comment]
感谢提供方案，openCC的如果会退出的 话，直接删除就可以，
