### ISSUE TITLE
关于Android端同文输入法无法点击候选词上屏的问题

### ISSUE THREAD

**Issue by Lyckerr** [SivanLaai/rime-pure#69]
开发者你好。我正在使用Android端的同文输入法3.2.2，在安装并使用您发布的1.1.6版四叶草九宫格输入方案+同文风优化版皮肤时，无法通过点击候选词上屏。在点击候选词时，编码区会追加候选词对应位置的数字。如输入“你好”，编码区为64426，点击第一个候选词后，编码区变为644261.详情参考如下录屏：

https://user-images.githubusercontent.com/33254847/170863319-488a0009-7f16-4243-968f-1aa820c05389.mp4

**Comment by Eyion** [comment]
试试在键盘设置将点击候选词这个选项打开，应该能解决你的问题。
