### ISSUE TITLE
无法通过打字来输入表情

### ISSUE THREAD

**Issue by funnycups** [SivanLaai/rime-pure#71]
如下图

![Screenshot_20220722_110109](https://user-images.githubusercontent.com/105932603/180353545-848b1d5f-9035-4b33-8e35-e096c52f5948.jpg)

**Comment by admin05** [comment]
我pc端用四叶草拼音也打不出xiaoku表情

**Comment by SivanLaai** [comment]
是不是没有开启表情，看下这个表情开关，默认是没有开启的。

**Comment by admin05** [comment]
表情开关在哪里呢？

**Comment by funnycups** [comment]
> 是不是没有开启表情，看下这个表情开关，默认是没有开启的。

是说这个吗，是开启的，但还是无法打表情
![Screenshot_20220803_224634](https://user-images.githubusercontent.com/105932603/182638165-1808dd42-41fe-43f8-9ed1-6414f38fc7ef.jpg)

**Comment by TingTing1990** [comment]
应该是删了opencc文件部署没有表情文件了

**Comment by SivanLaai** [comment]
下载最新的使用最新的文件，然后删除build opencc重新部署

**Comment by SivanLaai** [comment]
这个问题我分析了，应该是冲突引起的，

**Comment by AilurusRedPanda** [comment]
同样的问题，Color OS 13.0，用的最新的文件，反复删除部署也没用

**Comment by GeeSko** [comment]
同问怎么解决 本来可以用 表情和符号都可以使用 但现在一更新到最新1.1.7 覆盖之后就显示不出来了
