### ISSUE TITLE
为什么小狼毫在输入一个字母 d 的时候候选字是空白呢，没有出现“的、地、到”等候选字。

### ISSUE THREAD

**Issue by admin05** [SivanLaai/rime-pure#73]
为什么四叶草拼音在输入一个字母 d 的时候候选字是空白呢，没有出现“的、地、到”等候选字。别的字母比如 b 、a 这些都有候选字出现。我改用明月拼音就正常。

**Comment by SivanLaai** [comment]
这个问题，现在已经解决，是因为词库的问题，请看issue 81
