### ISSUE TITLE
如果我想切换英文，输入带英文词库，应该怎么做

### ISSUE THREAD

**Issue by AP0rPi7uQ9** [SivanLaai/rime-pure#76]
中文现在输入没什么问题，我想切换英文d时候，输入的候选词都是英文单词，应该怎么实现呢。。。小白求教

**Comment by SivanLaai** [comment]
这个是需要添加英文方案的，我看能否也加上，好像我记得rime官方是有方案的，我给加过来

**Comment by SivanLaai** [comment]
如果需要英文单词输入的话，可以使用（rime-easy-en）[https://github.com/BlindingDark/rime-easy-en]，如果是需要混输的话可以在（这个方案）[https://github.com/sdadonkey/rime-english]修改一下词库
