### ISSUE TITLE
有个小瑕疵，候选框的下拉键竟然跳转到了emoji

### ISSUE THREAD

**Issue by AP0rPi7uQ9** [SivanLaai/rime-pure#77]
有个小瑕疵，候选框的下拉键竟然跳转到了emoji。
比如输入【你好】，候选框有向右和向下的箭头，当点击向下的箭头，竟然跳转到emoji了，难道不应该跳转到更多候选词的下拉框吗

**Comment by SivanLaai** [comment]
可以反馈截图吗
