### ISSUE TITLE
trime 3.2.8 自然码输入错误

### ISSUE THREAD

**Issue by GitHubd3b7c** [SivanLaai/rime-pure#78]
按照 [教程](http://www.sivanlaai.top/pages/7128fc/#%E5%B0%8F%E7%8B%BC%E6%AF%AB-pc%E7%AB%AF) 安装好配置后，只能使用空格键入文字，手动点击候选词只会输入候选词所对应序号的数字
已尝试使用四叶草全拼、小鹤双拼无此情况

**Comment by GitHubd3b7c** [comment]
譬如图一我想输入”狼毫“的话需要在候选栏进行点击，但点击结果如图二所示
![1](https://user-images.githubusercontent.com/33088850/194267751-8bfe2038-be84-4a7a-b9e4-dd337504ffb6.jpg)
![2](https://user-images.githubusercontent.com/33088850/194267802-8668d22e-f94d-4a13-b272-2c6913d067fc.jpg)

**Comment by SivanLaai** [comment]
这个问题以前出现过，有问题可以先找close若issue，https://github.com/SivanLaai/rime-pure/issues/41

**Comment by GitHubd3b7c** [comment]
感谢您的回复，我找到了问题的所在，[自然码双拼配置文件](https://github.com/SivanLaai/rime-pure/blob/65c4c48a268cdff34d4f9640f13eab3ac2335b36/schemes/%E8%87%AA%E7%84%B6%E7%A0%81%E5%8F%8C%E6%8B%BC/double.schema.yaml#L50) 中
`alphabet: 'zyxwvutsrqponmlkjihgfedcba1234567890'`
更改为
`alphabet: 'zyxwvutsrqponmlkjihgfedcba'`
就能解决
请问`alphabet`中的数字是有意为之吗，因为对比其它 Rime 自然码配置后发现都没有包含数字，只有包含大小写字母的
