### ISSUE TITLE
四叶草九宫格的配置文件好像出了一点点错误

### ISSUE THREAD

**Issue by Steven52065** [SivanLaai/rime-pure#79]
https://github.com/SivanLaai/rime-pure/blob/master/trime/rime/%E5%90%8C%E6%96%87%E9%A3%8E%E5%A2%9E%E5%BC%BA%E7%89%88.trime.yaml

因为我用的是同文增强，在使用第三行最左边那个显示为“......”的按键，实际输出的却是^，不知道是故意为之还是单纯的手误输错
在将https://github.com/SivanLaai/rime-pure/blob/master/trime/rime/%E5%90%8C%E6%96%87%E9%A3%8E%E5%A2%9E%E5%BC%BA%E7%89%88.trime.yaml 的2243行修改为      - {click: "^", label: " ……", width: *NUM_SYM_W, key_text_offset_x: 3, key_symbol_offset_x: -12, key_symbol_offset_y: 16, send_bindings: false, long_click: "(){Left}", swipe_left: "(", swipe_right: ")", key_symbol_color: key_symbol_color, key_back_color: szbdb, key_text_size: 16}
就正常了
（刚开始使用rime，如有错误望大佬谅解）

**Comment by SivanLaai** [comment]
长时间没有回应，先关闭
