### ISSUE TITLE
四叶草地球拼音有误

### ISSUE THREAD

**Issue by warm-ice0x00** [SivanLaai/rime-pure#81]
包括四叶草拼音中已修复的含“弹”的词（“弹出”“弹射”“弹性”“反弹”中“弹”的拼音均为dàn）和“奇数”“奇偶”（qí），还有“帧”（zhèn）、“幀”（zhèng）、银行（xíng）等，可能上游拼音库需要更新。另外，“嗯”在其它输入法中拼音一般为en，否则双拼打不出“嗯”。

**Comment by SivanLaai** [comment]
感谢付出，这一块工作四叶草这边已经解决了，你可否参照四叶草这边的工作提供一份正确的词典，当前由于其它事情没有时间。

**Comment by warm-ice0x00** [comment]
用[深蓝词库转换](https://github.com/studyzy/imewlconverter)转换了华宇拼音7.3.0.296的系统词库（[下载](https://drive.google.com/file/d/1en5jM9jbd4hQ7lvG_MXZBycT2wP81LNY)），由于原词库中的单字大多读音有误，筛选出了两字及以上纯汉字词语，去重并按全拼升序和词频降序排序，可以代替四叶草拼音除单字外的词库。由于词库中部分词语的读音与[pypinyin](https://github.com/mozillazg/python-pinyin)的转换结果不同，加声调需手动操作，暂时没加声调。
