### ISSUE TITLE
感谢好物，已捐赠，顺便提几个问题

### ISSUE THREAD

**Issue by TingTing1990** [SivanLaai/rime-pure#85]
感谢大佬的付出，反馈几个问题：

1. 如果在数字键盘下隐藏键盘，再拉起来是主键盘下点击候选状态栏“中英”键“英”的状态（有时候全新拉起键盘也是在选的方案的这个状态而不是方案的中文模式）
2. 九宫数字键盘状态下点击“中”的按钮都是回26键英文模式（九宫数字键盘下是否不应该有“中”按钮，因为有返回了，或者是转回九宫中文模式？）
3. 九宫上滑除了分词的数字１外其他的上滑都不上屏
4. 九宫状态下点击状态栏的中英切到的是数字键盘（不知道是Bug还是，感觉在九宫输入法下在状态栏里不显示中英要好些）
5. 九宫的26键盘英文第4行有7个按键，空格是不是太长了？可以适当调整空格的长度给其他按键

感谢！

**Comment by SivanLaai** [comment]
这一块确实需要优化，您可以出一个调整方案嘛，或者您这边要是有一定的调试能力，也欢迎一起参与到项目里面来。

**Comment by TingTing1990** [comment]
感谢，目前正在看相关文档，但是还不具备修改的能力，只能提出调整方案，目前个人觉得主要的2个问题和1个Bug是：
1、九宫输入法的英文模式（实际使用是点“中/en”实现的），配置直接是调用的<jiugong_number>，这里应该是不正确的，不然一些输入框强制因为或者返回英文都回出现这个数字键盘
解决方案：指定26键的英文键盘，我之前修改了<jiugongLetter>，但是不生效，不太懂
2、九宫键盘 -点击数字键盘-再点击<中>回到的是26键的英文键，感觉这个不太合理，不知道能否解决，不能解决的话建议是将这个键改了，因为已经有返回了
3、Bug：九宫上滑除了分词的数字１外其他的上滑都不上屏

目前基于1的问题暂时将<reset_ascii_mode: false #显示键盘时重置为中文状态>改为true使用了

希望大佬能优化调整

**Comment by TingTing1990** [comment]
大佬有时间优化调整吗？

**Comment by SivanLaai** [comment]
暂时我是没有时间弄，我看下这几点
1.这个是因为是九宫模式，你说的修改是默认在九宫模式下默认为全英文键盘输入吗？
2.第二点这个我是参考百度输入法改的，如果要改的话有什么建议不
3.这个我这是可以的，你设置是什么

**Comment by SivanLaai** [comment]
可以把优化方案也 写出来，说不定有其他乐于分享的人改了，我有时间也可以往合理的方向直接改

**Comment by TingTing1990** [comment]
非常感谢，您可以有时间的时候再优化修改：
1、是的

2、可以将“中”键改成“+/-”，“*//”，“=”，我传了个讯飞输入法九宫数字的布局

<img width="831" alt="CleanShot 2022-12-30 at 12 37 52@2x" src="https://user-images.githubusercontent.com/51083586/210035202-4032a061-87fe-48c5-b342-afc3e4791f84.png">

3、我是安全使用你的配置，我录制了个视频，可以看下，谢谢！

https://user-images.githubusercontent.com/51083586/210035217-aa6904fd-db2b-45df-a1ed-ed04d99ddbb1.mp4

**Comment by SivanLaai** [comment]
暂时我是没有时间弄，我看下这几点
1.这个叫作ascii码键盘，不能直接调用其他的键盘，和键盘的中/En是两个概念，这个本质其实就是把九官格的ascii模式显示出来了
2.这个可以改
3.你用的什么版本的同文？

**Comment by SivanLaai** [comment]
第三个功能我尝试了下，如果一开始就想输入上滑2的话会失败，这个应该是同文层面的问题，配置是没有问题的，这个功能暂时先不用。如果是先上滑1的话，后面的数字是可以上滑的。

**Comment by TingTing1990** [comment]
1、感谢
2、感谢
3、确实是描述的问题，从1开始上滑就没问题，我用的是最新版本的同文输入法，从F-d下载的

**Comment by SivanLaai** [comment]
你从最新的源码里面把schemes 和 同文的主题更新一下。https://github.com/SivanLaai/rime-pure#%E6%9B%B4%E6%96%B0%E5%8E%86%E5%8F%B2

**Comment by TingTing1990** [comment]
已经更新，2.3没问题，1这个问题“把这个中/英切换在配置里面取消掉”应该是没用的，你一旦在九宫数字键盘里缩回键盘，如果开启了记住键盘，那么再次拉起的键盘就是九宫的ascii码键盘，向您上面说的：[这个叫作ascii码键盘，不能直接调用其他的键盘]，但是我在配置文件里看到九宫键盘的ascii码键盘调用的是jiugong_number，如图：
<img width="823" alt="这个叫作ascii码键盘，不能直接调用其他的键盘，" src="https://user-images.githubusercontent.com/51083586/210074574-d10ff966-2c26-4098-81b5-489e3c47a24d.png">

**Comment by SivanLaai** [comment]
好的，感谢测试，这个功能我改回来了。这个ascii模式其实这个没有调用jiugong_number这个键盘，是把ascii模式显示出来了而已，键盘还是原先的键盘，只不过有ascii模式。

**Comment by TingTing1990** [comment]
最新的
jiugong_number:
    ascii_mode: 1 # 这个是ascii的键盘模式，为0切换ascii模式则会加载ascii_keyboard所指定的键盘
2255行要改成1，不然九宫切到数字键盘会是“中”状态，点击数字是打字

PS：九宫如果英文键盘不能指定26键盘的话最好把149行的改为true，这样九宫每次拉起就会是中文，不会记录西文状态下的错误情况
reset_ascii_mode: true #显示键盘时重置为中文状态

PS2：目前【reset_ascii_mode: true #显示键盘时重置为中文状态】这个好像是对整个输入法有效的，如果改为26键盘的中文键盘的话也是强制中文了，但是26中文键盘的英文状态是没问题，不知道这个字段配置是否能根据输入法设置，九宫强制中文，26键盘拼音不强制中文
