### ISSUE TITLE
同文输入法，3.2.9版本

### ISSUE THREAD

**Issue by WvvvWv** [SivanLaai/rime-pure#87]
**提交issue**
把问题清晰的描述清楚

**问题复现（方便的话可以添加现象的截屏/视频方便描述）：**
复现步骤:
1. 进入 将配置复制到rime目录下
2. 点击 部署按钮
3. 出现问题 同文输入法就闪退了

**正确的结果**
正确的结果是什么样，可以清晰的描述出来。

**使用设备情况（请完整填写如下信息）：**
 - 设备型号： 三星S22U
 - 操作系统： 安卓
 - Rime软件名称和版本：同文 3.2.9
 - 输入方案：还未选择方案，仅在部署时就闪退
 - 使用皮肤：还未选择方案，仅在部署时就闪退

**其他信息**

**Comment by SivanLaai** [comment]
把build目录删除，然后重新部署



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月03日 10:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [SivanLaai/rime-pure] 同文输入法，3.2.9版本 (Issue #87) |

提交issue
把问题清晰的描述清楚

问题复现（方便的话可以添加现象的截屏/视频方便描述）：
复现步骤:

进入 将配置复制到rime目录下
点击 部署按钮
出现问题 同文输入法就闪退了

正确的结果
正确的结果是什么样，可以清晰的描述出来。

使用设备情况（请完整填写如下信息）：

设备型号： 三星S22U
操作系统： 安卓
Rime软件名称和版本：同文 3.2.9
输入方案：还未选择方案，仅在部署时就闪退
使用皮肤：还未选择方案，仅在部署时就闪退

其他信息

**Comment by WvvvWv** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    我刚刚试过了，还是不行
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年1月3日 12:10
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [SivanLaai/rime-pure] 同文输入法，3.2.9版本 (Issue #87)
        
      
    
  
  
把build目录删除，然后重新部署



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月03日 10:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [SivanLaai/rime-pure] 同文输入法，3.2.9版本 (Issue #87) |

提交issue
把问题清晰的描述清楚

问题复现（方便的话可以添加现象的截屏/视频方便描述）：
复现步骤:

进入 将配置复制到rime目录下
点击 部署按钮
出现问题 同文输入法就闪退了

正确的结果
正确的结果是什么样，可以清晰的描述出来。

使用设备情况（请完整填写如下信息）：

设备型号： 三星S22U
操作系统： 安卓
Rime软件名称和版本：同文 3.2.9
输入方案：还未选择方案，仅在部署时就闪退
使用皮肤：还未选择方案，仅在部署时就闪退

其他信息

**Comment by WvvvWv** [comment]
> 

我刚刚试过了，删除build目录，进入同文点击部署还是会闪退

**Comment by TingTing1990** [comment]
删除opencc和lua文件夹
