### ISSUE TITLE
[Rime3.2.10][四叶草九宫方案][无法使用九宫]已解决

### ISSUE THREAD

**Issue by guocuixia** [SivanLaai/rime-pure#88]
九宫格无法调出

**使用设备情况（请完整填写如下信息）：**
 - 设备型号： Huawei p 40 Pro 5G
 - 操作系统： 安卓
 - Rime软件名称和版本：同文 3.2.10
 - 输入方案：四叶草九宫 
 - 使用皮肤：同文增强版

**其他信息**
![Screenshot_20230105_141557_com osfans trime](https://user-images.githubusercontent.com/81362502/210714728-a0bec8ae-0321-480c-8955-f12abdb17990.jpg)
![Screenshot_20230105_141604_com osfans trime](https://user-images.githubusercontent.com/81362502/210714732-a1c29448-ebe4-48c3-8bf2-caaa5848e664.jpg)

**Comment by guocuixia** [comment]
![Screenshot_20230105_142136_com tencent mobileqq](https://user-images.githubusercontent.com/81362502/210714979-f196c2a0-5f58-4186-ab1b-896d05f4ccf8.jpg)

**Comment by guocuixia** [comment]
重新安装3.2.5可以使用

**Comment by TingTing1990** [comment]
3.2.10更新了个寂寞，3.2.9没问题，更新了部署直接出问题，向下兼容性太差了

**Comment by guocuixia** [comment]
> 

我是鸿蒙2.0 
 3.2.9不能使用
 3.2.8无法切换皮肤但感觉输入更流畅 输入不会显示数字字符(挺好)
 3.2.7可用
