### ISSUE TITLE
[Rime3.2.7][四叶草九宫][符号使用效率和手机自带搜索框输入问题]

### ISSUE THREAD

**Issue by guocuixia** [SivanLaai/rime-pure#89]
**提交issue*

**问题复现：**
复现步骤:
1. 进入 '符号'
2. 点击 '选中需要的符号'
3. 无法自动返回，需要手动返回，

**正确的结果**
1.进入符号第一版是常用符号，
2.在选择需要的符号后可以自动返回输入界面，手动返回体验不好非常影响效率。

**使用设备情况：**
 - 设备型号： Huawei p40 Pro 5G
 - 操作系统： 鸿蒙2.0 
 - Rime软件名称和版本：同文 3.2.7
 - 输入方案：四叶草九宫
 - 使用皮肤：同文增强版

**其他问题**
>手机自带下拉搜索框输入时上屏的字出现错乱,无法顺畅使用搜索功能

所谓错乱是输入第一个字母显示的不是对应的字，需要在输入第一个字母后，从第二个字母开始才能正常输入显示，那么会导致每次输入后必须删除第一个字后才能再进行搜索

例如:在搜索栏里搜:"文件管理"，输入第一个字文的拼音首字母"w'，搜索栏直接上屏显示为"我"，继续输入en上屏显示为"我懂"，正确应该是"文",
处理方法:需要在第一个w之后继续输入:"wen jian guan li"才能显示

>附件：
1.图片为对比小艺输入法的符号界面
2.视频为搜索框问题

![Screenshot_20230105_215057_com android chrome_edit_33155808037127](https://user-images.githubusercontent.com/81362502/210805484-2f31c347-b62b-4fcb-9af2-904a9b31ecd7.jpg)
![Screenshot_20230105_214958_com android chrome_edit_33196531503788](https://user-images.githubusercontent.com/81362502/210805511-cd8d3131-06d9-472a-9abc-73adfd85792e.jpg)

https://user-images.githubusercontent.com/81362502/210805834-6e833e80-b9db-422f-9133-ffedb4f93d84.mp4

**Comment by SivanLaai** [comment]
1.进入符号第一版是常用符号，（这个可以修改一下，如果可以的话，自己修改常用的符号也是可以的，直接修改同文主题的文件，然后重新部署）
2.在选择需要的符号后可以自动返回输入界面，手动返回体验不好非常影响效率。（这个是在同文端的设置的功能，我看一下同文端是不是支持点选返回）
3.这个问题应该是错乱配置引起的，可以把build备份后删除重新部署试一下
