### ISSUE TITLE
进入更多符号页后悬浮窗消失

### ISSUE THREAD

**Issue by chenxiex** [SivanLaai/rime-pure#90]
trime版本3.2.9，搭配最新的release，同文风增强版主题
长按更多进入符号页之后，返回字母页，此时使用拼音输入，用于显示拼音的悬浮窗消失，只留下显示候选词的框。截图对比：
![Screenshot_20230119_150930_org mozilla fenix_edit_371650577000060](https://user-images.githubusercontent.com/28776935/213378106-e9f47497-f0e7-45d3-b2df-c6b9ed868fa7.jpg)
![Screenshot_20230119_150858_org mozilla fenix_edit_371664961697975](https://user-images.githubusercontent.com/28776935/213378090-ead6bc28-80ad-4302-8bfd-226909277cad.jpg)

**Comment by SivanLaai** [comment]
这个问题重新选择一下方案可以规避，目前来看应该是3.2.9引入的问题，感谢反馈
