### ISSUE TITLE
希望在同文增强版皮肤里把“符号”按键加回来

### ISSUE THREAD

**Issue by Lake-x** [SivanLaai/rime-pure#91]
**提交issue**
同文增强版皮肤里有没“符号”按键，输入符号需要跳到“更多”，对于经常使用常规符合来说非常不方便

**正确的结果**
建议恢复符号按钮，像trime和tongwenfeng那样

**使用设备情况（请完整填写如下信息）：**
 - 设备型号： Huawei View 20
 - 操作系统： 安卓
 - Rime软件名称和版本：同文 3.2.10
 - 输入方案：极点五笔
 - 使用皮肤：同文增强版

**其他信息**

**Comment by SivanLaai** [comment]
你下以前的版本就可以，这个不会影响
