### ISSUE TITLE
同文风增强版默认26键方案无法长按打出中文？！符号

### ISSUE THREAD

**Issue by cpfy** [SivanLaai/rime-pure#92]
**提交issue**

如题，在中文模式下，长按 `，` 与 `。` 得到的符号均为英文的感叹号、问号

**问题复现（方便的话可以添加现象的截屏/视频方便描述）：**

<img src="https://user-images.githubusercontent.com/30110832/225847611-4cf587bc-9616-4937-81cc-bbcf38c1425f.jpg" width="45%" height="40%" />|<img src="https://user-images.githubusercontent.com/30110832/225847625-b2812acf-4c2e-40c7-95f3-a8183a2d2507.jpg" width="45%" height="40%" />

左图是英文输入模式，右图中文模式。

逗号、句号均可正确打出，同时能够看到预览时即可切换，但长按时对应的问号与感叹号均无变化，也无法正确打出

**正确的结果**

应当能够长按正确打出中文的问号 `？` 、感叹号 `！`

**使用设备情况：**

 - 操作系统： 安卓
 - Rime软件名称和版本：同文 3.2.11
 - 输入方案：四叶草拼音
 - 使用皮肤：同文增强版

**Comment by SivanLaai** [comment]
不要用最新的，3.2.9就行

**Comment by cpfy** [comment]
> 不要用最新的，3.2.9就行

我的 trime 3.2.8-3.2.10 版本用这个方案部署之后都是直接闪退，换到3.2.7确实不存在这个问题了
