### ISSUE TITLE
3.2.9-3.2.11  同文风增强版 笔画输入方案切换英文后就切换不回来了。

### ISSUE THREAD

**Issue by hrxing** [SivanLaai/rime-pure#93]
**提交issue**
笔画输入方案，同文风增强版主题；在笔画输入切换英文输入后，再切回来，会显示成拼音九宫格界面，但实际九宫格输出为数字，其他

**问题复现（方便的话可以添加现象的截屏/视频方便描述）：**
复现步骤:
1. 

https://user-images.githubusercontent.com/106504301/226544896-4d3190b0-6621-413b-a70d-03da28f3b090.mp4

2. 如视频所示，英文切换回来不是原来笔画输入模式，而是拼音九宫格。

**正确的结果**
从笔画输入切换英文输入后，再切回来应该是笔画输入模式

**使用设备情况（请完整填写如下信息）：**
 - 操作系统： 安卓
 - Rime软件名称和版本：同文 3.2.9
 - 输入方案：五笔画
 - 使用皮肤：同文增强版

**Comment by SivanLaai** [comment]
你方案是用的谁的

**Comment by hrxing** [comment]
https://rime.im/download/

**Comment by hrxing** [comment]
> 你方案是用的谁的

https://rime.im/download/

**Comment by zslqhua** [comment]
请教一下，我想在安卓手机上安装它。结果第一步就难倒我了。“备份sdcard\rime 文件夹”，我不知道这个文件夹在哪里！！！

**Comment by hrxing** [comment]
> 请教一下，我想在安卓手机上安装它。结果第一步就难倒我了。“备份sdcard\rime 文件夹”，我不知道这个文件夹在哪里！！！

在手机存储里啊，你用手机自带的“文件管理”打开就看得到了。

**Comment by zslqhua** [comment]
我手机华为的。在档案管理中没有找到这个文件夹！我自建了一个。但，复制后打开自建的文件夹却没有反应。不知所措了......

**Comment by zslqhua** [comment]
经过一番摸索，原来，这东西是要连电脑进行操作。所以，我连上电脑之后，看到了这个文件夹了，磕磕碰碰地安装进去了。虽有瑕疵，却也达到了我的预期使用目的。多谢开发者！

**Comment by SivanLaai** [comment]
> > 你方案是用的谁的
> 
> https://github.com/rime/rime-stroke

这个键盘加入应该是这个按钮的设置问题，后续有时间 改一下

**Comment by SivanLaai** [comment]
版本最好不要使用3.2.9以上的，建议的是3.2.4-3.2.9，同文的版本不是越新越好，最近改动的有点大

**Comment by hrxing** [comment]
> > > 你方案是用的谁的
> > 
> > 
> > https://github.com/rime/rime-stroke
> 
> 这个键盘加入应该是这个按钮的设置问题，后续有时间 改一下

十分感谢
