### ISSUE TITLE
安卓10 同文输入法3.2.2 五笔字根皮肤使用请教

### ISSUE THREAD

**Issue by jim1th** [SivanLaai/rime-pure#96]
你好，辛苦作者了，受益良多，就是本人入门学习五笔输入法，希望可以用到字根配色，方案选择尝试了**qq五笔，极点五笔及混拼**配合**同文增强版皮肤**，使用**五笔白色**配色调不出说明文档中的字根配色。

请问如何说明文档中的字根皮肤该如何正确调出？

多谢！

**使用设备情况（请完整填写如下信息）：**
 - 设备型号： Huawei Mate 30 Pro 5G
 - 操作系统： 安卓
 - Rime软件名称和版本：同文 3.2.2
 - 输入方案：极品五笔
 - 使用皮肤：同文增强版

**Comment by zslqhua** [comment]
在这里，搭个顺风车。我在mate 9上也安装了同文。可是遇到了蛮多的困难。比如，想要切换四叶草拼音和极品五笔时，却不能正常切换。切换窗口只有一半，无法操作。不过我只看中五笔，也就够了，在这里感谢开发者的辛勤付出！

**Comment by SivanLaai** [comment]
对于安装有什么问题可以先看一下这个B站视频 https://www.bilibili.com/video/BV1YA411z7Um/?spm_id_from=333.999.0.0。
字根调不出来的话有需要从设置里面进入，
设置：全键盘状态下按?123键下滑，九宫格状态下按带设置符号⚙的按键，既可进入设置页面

**Comment by jim1th** [comment]
安装方面是按照文档正常安装的，就是不知道怎么使用五笔字根这个主题，默认方案中只有五笔白色这个配色，但使用时和其他皮肤只有颜色区别，没有字根显示，查看了同文风增强版.trime.yaml，里面有五笔助记方案，但似乎默认不生效。
![Snipaste_2023-04-18_01-26-59](https://user-images.githubusercontent.com/117856429/232565458-21b17d62-19eb-441a-b47e-5fa274d2c142.png)
![Snipaste_2023-04-18_01-28-19](https://user-images.githubusercontent.com/117856429/232565530-c2af0397-0de3-4e6d-88df-60d7aed93ee4.png)

**Comment by ISouthRain** [comment]
> jim1th

同求, 你解决了吗?
