### ISSUE TITLE
有一些想请教的地方

### ISSUE THREAD

**Issue by jogGUY** [SivanLaai/rime-pure#99]
![Screenshot_2023-05-13-16-32-32](https://github.com/SivanLaai/rime-pure/assets/108516858/88563786-b0e1-4e54-9665-abc3c4bc2c89)
图中的输入法版本是同文输入法3.2.6，启用的皮肤是”同文风增强版“，有点不太明白：
1. 为何键盘上方的选择栏那里会有奇怪的挡字的小黑块？
2. 那个”→符 无符“和”→😑 😁“是什么作用？
3. 启用”同文风增强版“这个皮肤之后应该在哪里切换输入方案和键盘外观呢？主要是”同文风“这个皮肤左下角长按就可以切换比较方便测试，但是换到这个皮肤就迷茫了。
4. 要切换输入法是不是真的得跑到系统设置那里切换而不是某个键长按就可以切换？产生这个问题的原因是现在还在和同文的磨合期，之前用着的是谷歌输入法。比如说同文的滑动输入我不太了解该怎么弄、每个键的附带字符得长按而不能上划或者按shift输入我也不太习惯......

另外，貌似本项目的仓库里没有”五笔字根“”炫彩“”讯飞默认皮肤“”极致简约“这些皮肤啊，是我看漏了哪里还是之前有后来剔除了呢？

还有一个，想问一下作者有没有考虑做14键之类的键盘方案呢？

**Comment by zslqhua** [comment]
我遇到这样的问题：输入方案我选择了四叶草九宫格，也重新布置了，可还是全键盘界面。不知道为什么会这样......

**Comment by SivanLaai** [comment]
1。这个皮肤的原因，背景不太一样，还是因为Trime变动较大引起的，你可以用其他的皮肤
2。表示数学符号和表情包开关
3。看页面说明
4。对，因为考虑大家不会经常换
5。这个在设置里面设置

**Comment by SivanLaai** [comment]
> 现在很蛋疼的是九宫格皮肤在高版本会变得很奇怪......

高版本修改的比较激进，建议如果想使用本方案不要使用高版本
